# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks


default_language_version:
  python: python3 # Defaults to python2, so override it.

repos:
  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: e5dd9b832006b183d0428627a0b28412b940054c  # frozen: 6.4.0
    hooks:
      - id: buildifier
      - id: buildifier-lint
  # Check C/C++ code formatting using clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: d653a47db90d28365fb9f8a43e866d20f29b9ba4  # frozen: v18.1.5
    hooks:
      - id: clang-format
        args: ["-style=file"]  # Adjust arguments as needed
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 2c9f875913ee60ca25ce70243dc24d5b6415598c  # frozen: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
        exclude: ^bazel-execroot$
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: trailing-whitespace
  - repo: https://github.com/google/pre-commit-tool-hooks
    rev: efaea7c61c774c0b1a9805fd999e754a2d19dbd1  # frozen: v1.2.5
    hooks:
      - id: check-google-doc-style
      - id: markdown-toc
  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98  # frozen: v0.19.1
    hooks:
      - id: gitlint
