name: Pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.0

      # Automatically create GitHub suggestions for pre-commit file
      # changes as part of a pull request. Here we download the differences and
      # event configuration into an artefact to be used by this action.
      - name: Collect pre-commit output
        if: failure()
        run: |
          mkdir -p pre-commit-output
          git diff > pre-commit-output/diff
          cp $GITHUB_EVENT_PATH pre-commit-output/event
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: pre-commit output
          path: pre-commit-output/*
